spring:
    datasource:
        url: jdbc:mysql://localhost/ngf
        username: root
        password: system
        driver-class-name: com.mysql.jdbc.Driver
        initialize: true
    batch:
       job:
         enabled:false
    activemq:
       broker-url: tcp://localhost:61616
       queue:
         name: JMS_QUEUE_NAME
         
ngf:
   file:
      inbound:
           path: /c/LANDING_ZONE
      archive:
           enabled: true
           path: /c/ARCHIVE