logging:
  level: debug
  
server:
  ssl:
    enabled: false

spring:
    datasource:
        url: jdbc:mysql://localhost/springbatchdbtest
        username: root
        password: Nov@1234
        driver-class-name: com.mysql.jdbc.Driver
        initialize: true
    batch:
       job:
         enabled: false
    activemq:
       broker-url: tcp://localhost:61616
       queue:
         name: JMS_QUEUE_TEST
         
ngf:
   file:
      inbound:
           path: C:\\DATA\\NGF_CODEBASE\\NGF-173\\FILES\\TEST\\LANDINGZONE
      archive:
           enabled: true
           path: C:\\DATA\\NGF_CODEBASE\\NGF-173\\FILES\\TEST\\ARCHIVEZONE
